-- 11.	Ngày mua hàng (NGHD) của một khách hàng thành viên sẽ lớn hơn hoặc bằng ngày khách hàng đó đăng ký thành viên (NGDK).
CREATE TRIGGER TG_CAU11 ON HOADON
FOR INSERT,UPDATE
AS BEGIN
	DECLARE @MaKH CHAR(4), @NgHD SMALLDATETIME, @NgDK SMALLDATETIME
	SELECT @MaKH= ins.MAKH, @NgHD= INS.NGHD FROM inserted ins
	SELECT @NgDK=KH.NGDK FROM KHACHHANG KH WHERE KH.MAKH = @MaKH
	IF(@NgHD<@NgDK) BEGIN
		RAISERROR ('KHONG HOP LE',16,1)
		ROLLBACK TRAN
	END
	ELSE BEGIN
		PRINT 'HOP LE'
	END
END	
--12.	Ngày bán hàng (NGHD) của một nhân viên phải lớn hơn hoặc bằng ngày nhân viên đó vào làm.
CREATE TRIGGER TG_CAU12 ON HOADON
FOR INSERT, UPDATE
AS BEGIN
	DECLARE @NgHD SMALLDATETIME, @NgVL SMALLDATETIME
	SELECT @NgHD=ins.NGHD FROM inserted ins
	SELECT @NgVL=NV.NGVL FROM inserted ins, NHANVIEN NV WHERE ins.MANV=NV.MANV
	IF(@NgHD>=@NgVL) BEGIN
		PRINT 'HOP LE'
	END
	ELSE BEGIN
		PRINT 'KHONG HOP LE'
		ROLLBACK TRAN
	END
END
--13.	Trị giá của một hóa đơn là tổng thành tiền (số lượng*đơn giá) của các chi tiết thuộc hóa đơn đó.
CREATE TRIGGER INSERT_HOADON_C13
ON HOADON
FOR INSERT
AS
 UPDATE HOADON
 SET  TRIGIA=0
 WHERE SOHD=(SELECT  SOHD
    FROM  INSERTED)
 PRINT'DA INSERT 1 HOADON VOI TRIGIA BAN DAU LA 0 VND' 
 -------------
CREATE TRIGGER UPDATE_HOADON_C13
ON HOADON
FOR INSERT
AS
 UPDATE HOADON
 SET  TRIGIA=(SELECT TRIGIA
     FROM DELETED)
 WHERE SOHD=(SELECT  SOHD
    FROM  INSERTED)
 PRINT'DA UPDATE 1 HOADON VOI TRIGIA KHONG THAY DOI'
 -------------
CREATE TRIGGER INSERT_CTHD_C13
ON CTHD
FOR INSERT
AS
 DECLARE  @SL  INT,
   @GIA  MONEY,
   @SOHD INT

 SELECT @GIA=GIA,@SL=SL,@SOHD=SOHD
 FROM  INSERTED A, SANPHAM B
 WHERE A.MASP=B.MASP

 UPDATE HOADON
 SET  TRIGIA=TRIGIA+@SL*@GIA
  PRINT'DA INSERT 1 CTHD VA UPDATE LAI TRIGIA CUA HOADON TUONG UNG'
 --------------
CREATE TRIGGER DELETE_CTHD_C13
ON CTHD
FOR DELETE
AS
 DECLARE  @SL  INT,
   @GIA  MONEY,
   @SOHD INT

 SELECT @GIA=GIA,@SL=SL,@SOHD=SOHD
 FROM  DELETED A, SANPHAM B
 WHERE A.MASP=B.MASP

 UPDATE HOADON
 SET  TRIGIA=TRIGIA-@SL*@GIA
  PRINT'DA DELETE 1 CTHD VA UPDATE LAI TRIGIA CUA HOADON TUONG UNG'
 -------------------
CREATE TRIGGER UPDATE_CTHD_C13
ON CTHD
FOR UPDATE
AS
 DECLARE  @SL_CU INT,
   @SL_MOI INT,   
   @GIA_CU MONEY,
   @GIA_MOI MONEY,
   @SOHD_CU INT,
   @SOHD_MOI INT

 SELECT @GIA_CU=GIA,@SL_CU=SL,@SOHD_CU=SOHD
 FROM  DELETED A, SANPHAM B
 WHERE A.MASP=B.MASP
 
 SELECT @GIA_MOI=GIA,@SL_MOI=SL,@SOHD_MOI=SOHD
 FROM  INSERTED A, SANPHAM B
 WHERE A.MASP=B.MASP

 IF(@SOHD_CU=@SOHD_MOI)
  BEGIN
   UPDATE HOADON
   SET  TRIGIA=TRIGIA+@SL_MOI*@GIA_MOI-@SL_CU*@GIA_CU
   WHERE SOHD=@SOHD_CU
  END
 ELSE
  BEGIN
   UPDATE HOADON
   SET  TRIGIA=TRIGIA-@SL_CU*@GIA_CU
   WHERE SOHD=@SOHD_CU

   UPDATE HOADON
   SET  TRIGIA=TRIGIA+@SL_MOI*@GIA_MOI
   WHERE SOHD=@SOHD_MOI
  END
 PRINT'DA UPDATE 1 CTHD VA UPDATE LAI TRIGIA CUA HOADON TUONG UNG'
 -------------------
CREATE TRIGGER UPDATE_HOADON_C13
ON  HOADON
FOR  INSERT
AS
 DECLARE @GIA_CU MONEY,
   @GIA_MOI MONEY,
   @SOHD INT,
   @SL  INT
   
 SELECT @GIA_CU=GIA
 FROM  DELETED
 SELECT @GIA_MOI=GIA
 FROM  INSERTED

 SELECT @SOHD=SOHD,@SL=SL
 FROM  INSERTED A, CTHD B
 WHERE A.MASP=B.MASP

 UPDATE HOADON
 SET  TRIGIA=TRIGIA+@SL*(@GIA_MOI-@GIA_CU) 
 WHERE SOHD=@SOHD
  PRINT'DA UPDATE 1 HOADON VOI TRIGIA KHONG THAY DOI'
--14.	Doanh số của một khách hàng là tổng trị giá các hóa đơn mà khách hàng thành viên đó đã mua.
CREATE TRIGGER INSERT_KHACHHANG_C14
ON KHACHHANG
FOR INSERT
AS
 DECLARE @MAKH CHAR(4)

 SELECT @MAKH=MAKH
 FROM  INSERTED
 
 UPDATE KHACHHANG
 SET  DOANHSO=0
 WHERE MAKH=@MAKH

 PRINT 'DA INSERT 1 KHACHHANG MOI VOI DOANHSO BAN DAU LA 0 VND'
 ----------------
CREATE TRIGGER UPDATE_KHACHHANG_C14
ON KHACHHANG
FOR UPDATE
AS
 DECLARE @MAKH  CHAR(4),
   @DOANHSO_CU MONEY

 SELECT @MAKH=MAKH
 FROM  INSERTED
 
 SELECT @DOANHSO_CU=DOANHSO
 FROM  DELETED
 
 UPDATE KHACHHANG
 SET  DOANHSO=@DOANHSO_CU
 WHERE MAKH=@MAKH

 PRINT 'DA UPDATE 1 KHACHHANG'
 ----------------
CREATE TRIGGER INSERT_HOADON_C14
ON HOADON
FOR INSERT
AS
 DECLARE @TRIGIA MONEY,
   @MAKH CHAR(4)

 SELECT @MAKH=MAKH,@TRIGIA=TRIGIA
 FROM  INSERTED
 
 UPDATE KHACHHANG
 SET  DOANHSO=DOANHSO+@TRIGIA
 WHERE MAKH=@MAKH

 PRINT 'DA INSERT 1 HODON MOI VA UPDATE LAI DOANHSO CUA KH CO SOHD TREN'

 -----------
CREATE TRIGGER DELETE_HOADON_C14
ON HOADON
FOR DELETE
AS
 DECLARE @TRIGIA MONEY,
   @MAKH CHAR(4)

 SELECT @MAKH=MAKH,@TRIGIA=TRIGIA
 FROM  DELETED
 
 UPDATE KHACHHANG
 SET  DOANHSO=DOANHSO-@TRIGIA
 WHERE MAKH=@MAKH

 PRINT 'DA DELETE 1 HODON MOI VA UPDATE LAI DOANHSO CUA KH CO SOHD TREN'
 ---------------
CREATE TRIGGER UPDATE_HOADON_C14
ON HOADON
FOR UPDATE
AS
 DECLARE @TRIGIA_CU MONEY,
   @TRIGIA_MOI MONEY,
   @MAKH  CHAR(4)

 SELECT @MAKH=MAKH,@TRIGIA_MOI=TRIGIA
 FROM  INSERTED

 SELECT @MAKH=MAKH,@TRIGIA_CU=TRIGIA
 FROM  DELETED
  
 UPDATE KHACHHANG
 SET  DOANHSO=DOANHSO+@TRIGIA_MOI-@TRIGIA_CU
 WHERE MAKH=@MAKH

 PRINT 'DA UPDATE 1 HOADON MOI VA UPDATE LAI DOANHSO CUA KH CO SOHD TREN'